name: member_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter

  flutter_riverpod: ^1.0.3
  flutter_svg: ^1.0.0
  freezed_annotation: ^1.1.0
  intl: ^0.17.0
  rive: ^0.8.1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

  freezed: ^1.1.0

  lint: ^1.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/rive/
